version: "3.4"
services:
    backend.recycle:
        build: .
        
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Recycle@123"
            ACCEPT_EULA: "Y"









            
